// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace insurance_partners_management_system.Models;

[Table("PartnerInfo")]
[Index("ExternalCode", Name = "UQ__PartnerI__A93D2634D2443DDB", IsUnique = true)]
public partial class PartnerInfo
{
    [Key]
    public int IdPartner { get; set; }

    [Required]
    [StringLength(255, MinimumLength = 2)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(255, MinimumLength = 2)]
    public string LastName { get; set; }

    public string Address { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    [RegularExpression("^[0-9]{20}$", ErrorMessage = "PartnerNumber must be exactly 20 digits.")]
    public string PartnerNumber { get; set; }

    [Column("CroatianPIN")]
    [StringLength(11)]
    [Unicode(false)]
    [RegularExpression("^[0-9]{11}$", ErrorMessage = "CroatianPIN must be exactly 11 digits.")]
    public string CroatianPin { get; set; }

    [Required]
    [Range(1, 2, ErrorMessage = "PartnerTypeId must be 1 (Personal) or 2 (Legal).")]
    public int PartnerTypeId { get; set; }

    [Column(TypeName = "datetime")]
    [Required]
    public DateTime CreatedAtUtc { get; set; }

    [Required]
    [StringLength(255)]
    [EmailAddress(ErrorMessage = "Invalid email format.")]
    public string CreateByUser { get; set; }

    [Required]
    public bool IsForeign { get; set; }

    [Required]
    [StringLength(20, MinimumLength = 10)]
    public string ExternalCode { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    [RegularExpression("^[MFN]$", ErrorMessage = "Gender must be 'M', 'F', or 'N'.")]
    public string Gender { get; set; }
}
